testset:
  dataset: Dogs vs Cats
  description: TODO

  general:
    image_size: 256
    label_mapping:
      Cat: 0
      Dog: 1
    unknown: 255

  paths:
    annotations: 
      dir: ./server/static/testset/annotations/
      unl: unl.json
      train: train.json
      test: test.json
    models:
      raw: ./server/static/testset/models/testset_raw.pt
      trained: ./server/static/testset/models/testset_trained.pt
    images:
      raw_unl: ./data/PetImages/Unlabelled
      transformed_unl: ./server/static/testset/images_tranformed
      raw_test: ./data/PetImages/Test
      transformed_test: ./server/static/testset/images_test
      raw_train: ./data/PetImages/Train
      transformed_train: ./server/static/testset/images_train
    data:
      last_predictions: ./data/last_predictions.json
      train_results: ./data/train_results.json
      test_results: ./data/test_results.json
      predictions: ./data/predictions.json

  train:
    predictions: 48
    epochs: 10
    batch_size: 64

  # currently not used
  preprocessing:
    grayscale: False
    rescale_with_crop: False
    normalization: False
    centering: False
    standarization: False
    strict_balance: False
