testset:
  dataset: Dogs vs Cats
  description: TODO

  general:
    image_size: 256
    label_mapping:
      Cat: 0
      Dog: 1
    unknown: 255

  paths:
    annotations:
      dir: ./server/static/testset/annotations/
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models:
      raw: ./server/static/testset/models/testset_raw.pt
      trained: ./server/static/testset/models/testset_trained.pt
    images:
      raw_unl: ./data/PetImages/Unlabelled
      transformed_unl: ./server/static/testset/images_tranformed
      raw_test: ./data/PetImages/Test
      transformed_test: ./server/static/testset/images_test
      raw_train: ./data/PetImages/Train
      transformed_train: ./server/static/testset/images_train
      raw_validation: ./data/PetImages/Validation
      transformed_validation: ./server/static/testset/images_validation
    data:
      last_predictions: ./data/last_predictions.json
      train_results: ./data/train_results.json
      test_results: ./data/test_results.json
      predictions: ./data/predictions.json

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  # currently not used
  preprocessing:
    grayscale: False
    rescale_with_crop: False
    normalization: False
    centering: False
    standarization: False
    strict_balance: False

sushi_sandwiches:
  dataset: Sushi vs sandwiches
  description: TODO

  general:
    image_size: 256
    label_mapping:
      Sandwich: 0
      Sushi: 1
    unknown: 255

  paths:
    annotations:
      dir: ./server/static/sushi_sandwiches/annotations/
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models:
      raw: ./server/static/sushi_sandwiches/models/sushi_sandwiches_raw.pt
      trained: ./server/static/sushi_sandwiches/models/sushi_sandwiches_trained.pt
    images:
      raw_unl: ./data/SushiSandwich/unlabelled
      transformed_unl: ./server/static/sushi_sandwiches/images_tranformed
      raw_test: ./data/SushiSandwich/test
      transformed_test: ./server/static/sushi_sandwiches/images_test
      raw_train: ./data/SushiSandwich/train
      transformed_train: ./server/static/sushi_sandwiches/images_train
      raw_validation: ./data/SushiSandwich/valid
      transformed_validation: ./server/static/sushi_sandwiches/images_valid
    data:
      train_results: ./server/static/sushi_sandwiches/data/train_results.json
      test_results: ./server/static/sushi_sandwiches/data/test_results.json
      predictions: ./server/static/sushi_sandwiches/data/predictions.json

  train:
    predictions: 10
    epochs: 10
    batch_size: 128


cars_aircrafts:
  dataset: Cars vs Aircrafts
  description: TODO

  general:
    image_size: 256
    label_mapping:
      Aircraft: 0
      Car: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [cars_aircrafts, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      raw: [cars_aircrafts, models, cars_aircrafts_raw.pt]
      trained: [cars_aircrafts, models, cars_aircrafts_trained.pt]
    images:
      raw:  # data base prefix will be added
        unl: [CarsAircrafts, unlabelled]
        test: [CarsAircrafts, test]
        train: [CarsAircrafts, train]
        validation: [CarsAircrafts, valid]
      transformed:  # server base prefix will be added
        unl: [cars_aircrafts, images_tranformed]
        test: [cars_aircrafts, images_test]
        train: [cars_aircrafts, images_train]
        validation: [cars_aircrafts, images_valid]
    data:  # server base prefix will be added
      train_results: [cars_aircrafts, data, train_results.json]
      test_results: [cars_aircrafts, data, test_results.json]
      predictions: [cars_aircrafts, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  test:
    outputs: 6


audi_vs_bmw:
  dataset: Audi vs BMW
  description: TODO

  general:
    image_size: 256
    label_mapping:
      audi: 0
      bmw: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [audi_vs_bmw, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      raw: [audi_vs_bmw, models, audi_vs_bmw_raw.pt]
      trained: [audi_vs_bmw, models, audi_vs_bmw_trained.pt]
    images:
      raw:  # data base prefix will be added
        unl: [audi_vs_bmw, unlabelled]
        test: [audi_vs_bmw, test]
        train: [audi_vs_bmw, train]
        validation: [audi_vs_bmw, valid]
      transformed:  # server base prefix will be added
        unl: [audi_vs_bmw, images_tranformed]
        test: [audi_vs_bmw, images_test]
        train: [audi_vs_bmw, images_train]
        validation: [audi_vs_bmw, images_valid]
    data:  # server base prefix will be added
      train_results: [audi_vs_bmw, data, train_results.json]
      test_results: [audi_vs_bmw, data, test_results.json]
      predictions: [audi_vs_bmw, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  test:
    outputs: 6


male_vs_famale:
  dataset: Male vs Famale
  description: TODO

  general:
    image_size: 256
    label_mapping:
      famale: 0
      male: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [male_vs_famale, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      raw: [male_vs_famale, models, male_vs_famale_raw.pt]
      trained: [male_vs_famale, models, male_vs_famale_trained.pt]
    images:
      raw:  # data base prefix will be added
        unl: [MaleFamale, unlabelled]
        test: [MaleFamale, test]
        train: [MaleFamale, train]
        validation: [MaleFamale, valid]
      transformed:  # server base prefix will be added
        unl: [male_vs_famale, images_tranformed]
        test: [male_vs_famale, images_test]
        train: [male_vs_famale, images_train]
        validation: [male_vs_famale, images_valid]
    data:  # server base prefix will be added
      train_results: [male_vs_famale, data, train_results.json]
      test_results: [male_vs_famale, data, test_results.json]
      predictions: [male_vs_famale, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  test:
    outputs: 6