cats_vs_dogs:
  dataset: Dogs vs Cats
  description: "This dataset contains images of Dogs and Cats.
    Images have been splitted into 4 sets: unlabelled, validation, train
    and test with 3998, 3988, 11496, 7817 images respectively"

  general:
    image_size: 256
    label_mapping:
      Cat: 0
      Dog: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [cats_vs_dogs, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      best: [cats_vs_dogs, models, cats_vs_dogs_best.pt]
      training: [cats_vs_dogs, models, cats_vs_dogs_training.pt]
    images:
      raw:  # data base prefix will be added
        unl: [PetImages, unlabelled]
        test: [PetImages, test]
        train: [PetImages, train]
        validation: [PetImages, valid]
      transformed:  # server base prefix will be added
        unl: [cats_vs_dogs, images_tranformed]
        test: [cats_vs_dogs, images_test]
        train: [cats_vs_dogs, images_train]
        validation: [cats_vs_dogs, images_valid]
    data:  # server base prefix will be added
      train_results: [cats_vs_dogs, data, train_results.json]
      test_results: [cats_vs_dogs, data, test_results.json]
      predictions: [cats_vs_dogs, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  # currently not used
  preprocessing:
    grayscale: False
    rescale_with_crop: False
    normalization: False
    centering: False
    standarization: False
    strict_balance: False


cars_aircrafts:
  dataset: Cars vs Aircrafts
  description: Cars and Aircrafts dataset.

  general:
    image_size: 256
    label_mapping:
      Aircraft: 0
      Car: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [cars_aircrafts, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      best: [cars_aircrafts, models, cars_aircrafts_best.pt]
      training: [cars_aircrafts, models, cars_aircrafts_training.pt]
    images:
      raw:  # data base prefix will be added
        unl: [CarsAircrafts, unlabelled]
        test: [CarsAircrafts, test]
        train: [CarsAircrafts, train]
        validation: [CarsAircrafts, valid]
      transformed:  # server base prefix will be added
        unl: [cars_aircrafts, images_tranformed]
        test: [cars_aircrafts, images_test]
        train: [cars_aircrafts, images_train]
        validation: [cars_aircrafts, images_valid]
    data:  # server base prefix will be added
      train_results: [cars_aircrafts, data, train_results.json]
      test_results: [cars_aircrafts, data, test_results.json]
      predictions: [cars_aircrafts, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  test:
    outputs: 6


audi_vs_bmw:
  dataset: Audi vs BMW
  description: Dataset that contains images of BMW and Audi cars

  general:
    image_size: 256
    label_mapping:
      audi: 0
      bmw: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [audi_vs_bmw, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      training: [audi_vs_bmw, models, audi_vs_bmw_training.pt]
      best: [audi_vs_bmw, models, audi_vs_bmw_best.pt]
    images:
      raw:  # data base prefix will be added
        unl: [audi_vs_bmw, unlabelled]
        test: [audi_vs_bmw, test]
        train: [audi_vs_bmw, train]
        validation: [audi_vs_bmw, valid]
      transformed:  # server base prefix will be added
        unl: [audi_vs_bmw, images_tranformed]
        test: [audi_vs_bmw, images_test]
        train: [audi_vs_bmw, images_train]
        validation: [audi_vs_bmw, images_valid]
    data:  # server base prefix will be added
      train_results: [audi_vs_bmw, data, train_results.json]
      test_results: [audi_vs_bmw, data, test_results.json]
      predictions: [audi_vs_bmw, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  test:
    outputs: 6


male_vs_famale:
  dataset: Male vs Famale
  description: Males and Famales images.

  general:
    image_size: 256
    label_mapping:
      famale: 0
      male: 1
    unknown: 255

  paths:
    server_base: ['.', 'mlvt', 'server', 'static']
    data_base: ['.', 'data']
    annotations: # server base prefix will be added
      dir: [male_vs_famale, annotations]
      unl: unl.json
      train: train.json
      test: test.json
      valid: validation.json
    models: # server base prefix will be added
      training: [male_vs_famale, models, male_vs_famale_training.pt]
      best: [male_vs_famale, models, male_vs_famale_raw.pt]
    images:
      raw:  # data base prefix will be added
        unl: [MaleFamale, unlabelled]
        test: [MaleFamale, test]
        train: [MaleFamale, train]
        validation: [MaleFamale, valid]
      transformed:  # server base prefix will be added
        unl: [male_vs_famale, images_tranformed]
        test: [male_vs_famale, images_test]
        train: [male_vs_famale, images_train]
        validation: [male_vs_famale, images_valid]
    data:  # server base prefix will be added
      train_results: [male_vs_famale, data, train_results.json]
      test_results: [male_vs_famale, data, test_results.json]
      predictions: [male_vs_famale, data, predictions.json]
      last_user_test: [json, last_user_test.json]

  train:
    predictions: 10
    epochs: 10
    batch_size: 128

  test:
    outputs: 6